version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_playground
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5432:5432"
    volumes:
      - "./db.sql:/docker-entrypoint-initdb.d/db.sql"

